name: Trigger auto deployment for aca-az2003

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/aca-az2003-AutoDeployTrigger-dbf0ca8c-505b-4674-a1c1-27195cf5fece.yml'

  # Allow manual trigger 
  workflow_dispatch:
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.ACAAZ2003_AZURE_CREDENTIALS }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: az2003.azurecr.io
          registryUsername: ${{ secrets.ACAAZ2003_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.ACAAZ2003_REGISTRY_PASSWORD }}
          containerAppName: aca-az2003
          resourceGroup: AZ-2003
          imageToBuild: az2003.azurecr.io/aca-az2003:${{ github.sha }}
          
            

     

