# .github/workflows/dotnet-core.yml

name: Build and Publish .NET Core

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.x'

    - name: Restore NuGet packages
      run: dotnet restore
      working-directory: ./src # Specify the working directory for this step

    - name: Build .NET Core application
      run: dotnet build --configuration Release --no-restore
      working-directory: ./src # Specify the working directory for this step

    - name: Publish .NET application
      run: dotnet publish --configuration Release --output ./publish
      working-directory: ./src # Specify the working directory for this step

    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: dotnet-app
        path: ./publish
      working-directory: ./src # Specify the working directory for this step
